name: Create and publish a package
on:
    release:
        types: [ created ]
    workflow_dispatch:
jobs:
#    build-and-publish-linux:
#        runs-on: ubuntu-latest
#
#        steps:
#            -   name: Checkout
#                uses: actions/checkout@v2
#            -   name: Set up JDK 11
#                uses: actions/setup-java@v2
#                with:
#                    java-version: '11'
#                    distribution: 'adopt'
#            -   id: install-secret-key
#                name: Install GPG secret key
#                run: |
#                    cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
#                    gpg --list-secret-keys --keyid-format LONG
#            -   id: cache-gradle-linux
#                name: Cache gradle
#                uses: actions/cache@v2
#                with:
#                    path: |
#                        ~/.gradle/caches
#                        ~/.gradle/wrapper
#                        ~/.konan/cache
#                    key: ${{runner.os}}-build-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#            -   name: Check with gradle
#                run: ./gradlew check
#            -   id: publish-to-central
#                name: Publish with gradle
#                run: ./gradlew publish -Pgpg.passphrase='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}' -Possrh.username='${{ secrets.OSSRH_USERNAME }}' -Possrh.password='${{ secrets.OSSRH_PASSWORD }}' -Pnative.deploy=all
#                env:
#                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-and-publish-windows-linux:
        runs-on: windows-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   id: cache-gradle-windows
                name: Cache gradle
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                        ~/.konan/cache
                    key: ${{runner.os}}-build-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#            -   name: Check with gradle
#                run: ./gradlew check
            -   id: publish-to-central
                name: Publish with gradle
                shell: bash
                run: ./gradlew publish -Possrh.username='${{ secrets.OSSRH_USERNAME }}' -Possrh.password='${{ secrets.OSSRH_PASSWORD }}' -Pnative.deploy=all
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GPG_PRIV_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
                    GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    build-and-publish-macos:
        runs-on: macos-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   id: cache-gradle-macos
                name: Cache gradle
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                        ~/.konan/cache
                    key: ${{runner.os}}-build-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#            -   name: Check with gradle
#                run: ./gradlew nativeTest
            -   id: publish-to-central
                name: Publish with gradle
                run: ./gradlew publishNative -Possrh.username='${{ secrets.OSSRH_USERNAME }}' -Possrh.password='${{ secrets.OSSRH_PASSWORD }}' -Pnative.deploy=all
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GPG_PRIV_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
                    GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
